### ISSUE TITLE
Line breaks between every word

### ISSUE THREAD

**Issue by wedgiebee** [jaysan0/obsidian-theme#2]
Great theme! Not working for me on mac Obisidian v0.14.15 though if you check out the screenshot. I don't have any line breaks there so it should all just be one line 🤔 

<img width="320" alt="Screen Shot 2022-06-08 at 7 17 58 AM" src="https://user-images.githubusercontent.com/3342937/172639777-eb8aec51-fc54-4cb5-9cf7-b933a1e7d9e8.png">

**Comment by jaysan0** [comment]
Hello Sean,
thank you for your email. Apologies for the late reply, I have been busy
with exams. x(

I have addressed this issue in the latest release. Please update the theme
from Obsidian.

Thanks for reaching out and for your valuable feedback.

Regards,
Jaysan

**Comment by jaysan0** [comment]
I have addressed this issue in the latest release. Please update the theme from Obsidian. Thanks for the feedback.
